version: '3.8'

services:
  backend:
    image: cluebackend:1
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - target: 8094
        published: 8094
        protocol: tcp
        mode: host
    networks:
      - clue_net
  dbclases:
    image: postgres:15.0-bullseye
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_DB=cluedb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_clue_data:/var/lib/postgresql/data/pgdata
    networks:
      - tendencias_instituto_net
           
volumes:
  pg_clue_data:
    external: true

networks:
  clue_net:
    external: true

secrets:
  db_dev_pass:
    external: true  